config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',	 		to: 'static_pages#help'
  get '/about',	 		to: 'static_pages#about'
  get '/contact', 		to: 'static_pages#contact'
  get '/signup',	    to: 'users#new'
  get '/login',	    	to: 'sessions#new'
  post '/login',	    to: 'sessions#create'
  delete '/logout',	    to: 'sessions#destroy'
  resources :users 
  resources :blogs
  resources :videos
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@blogs = Blog.order("created_at DESC")
  	@videos = Video.order("created_at DESC")
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def blog_helper(index)
    @blogs = Blog.order('created_at DESC').first(1)
    @blog = @blogs.fetch(index, "No blog found")
  end

  def blog_title(index)
    @blogs = Blog.order('created_at DESC').first(1)
    if @blogs.any?
      @blog = @blogs.fetch(index, "No blog found")
      @blog.title
    end
  end

  def blog_text_teaser(index)
    @blogs = Blog.order('created_at DESC').first(4)
    if @blogs.any?
      @blog = @blogs.fetch(index, "No blog found")
      truncate(strip_tags(@blog.content.to_s), length: 300, separator: " ")
    end
  end

end

app/views/static_pages/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="container history">
  <div class="wrapper">
<h4 class="core-title text-center">Our History</h4>

    <ul class="history-timeline">
      <li>
        <div class="time">1998-2003</div>
        <p>The history of PEFA Church Kayole B dates back to March 1998 when Rev. and Mrs. Paul Munyiri founded the then Eastland Gospel Centre at Hot Sun Hall. The vision of Rev. Munyiri and the leadership was very clear: To make Eastland Gospel Centre be a Mission Centre church that would develop leaders and missionaries and release them to the field, serving God. As the ministry grew, a number of challenges were experienced and there were a lot of movements from one venue to another. Among the locations the Church found abode were Hot Sun Hall,the current Nasra Estate, Kayole 1 Social Hall before settling at the current location at Kayole,Rasta Stage, in 2003.</p>
      </li>
      <li>
        <div class="time">2003</div>
        <p>During the year 2003, the Church board made a decision to be part of a main stream church that the local leadership would be answerable to. It was becoming evident that there was a need to be in a larger family of believers, instead of continuing the solo pursuit of the mission. The Pastor and the leadership, after careful considerations, settled to approach PEFA, South East district Leadership to be considered for joining the PEFA family. This was finally approved by the district Board and the church was renamed as PEFA, Kayole B. It was put under probation for 6 months after which PEFA Kayole B was confirmed as a member of South East District PEFA Churches.</p>
      </li>
      <li>
        <div class="time">To the Future</div>
        <p>Join us in making and writing our future history.</p>
      </li>
    </ul>
  </div>
</div> 

<div class="container">
<section class="list--wrapper">
  <h4 class="core-title text-center">Our Core Values:</h4>
  <ul class="list">
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>We Are a Family</span></h2>
        <p class="list--link__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>Excellence in Service</span></h2>
        <p class="list--link__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>Sound Biblical Teachings</span></h2>
        <p class="list--link__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>A Learning Church</span></h2>
        <p class="list--link__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>God Centered Worship</span></h2>
        <p class="list--link__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
    <li class="list--item">
      <a href="javascript:void(0)" class="list--link">
        <h2 class="list--link__header"><span>Children Ministry</span></h2>
        <p class="list--link__description">Media queries are useful when you want to modify your site or app depending on a device's general type (sLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </a>
    </li>
  </ul>
</section>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Sample App</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="https://www.railstutorial.org/help">Rails Tutorial Help Page</a>
	To get help on this sample app,  see the
	<a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>book</a>
</p>

app/views/static_pages/home.html.erb
	<div class="row">
		<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		  <div class="carousel-inner">
		    <div class="item active">
		    	<%= image_tag("2021newbanner.png", class: "d-block w-100 c-image") %>
		    </div>
		    <div class="item">
		      <%= image_tag("carousel.jpg", class: "d-block w-100 c-image") %>
		    </div>
		    <div class="item">
		      <%= image_tag("carousel_1.jpg", class: "d-block w-100 c-image") %>
		    </div>

		    <div class="item">
		      <%= image_tag("carousel_2.jpg", class: "d-block w-100 c-image") %>
		    </div>

		    <div class="item">
		      <%= image_tag("carousel_5.jpg", class: "d-block w-100 c-image") %>
		    </div>
		  </div>
		  <a class="left carousel-control" href="#carouselExampleControls" role="button" data-slide="prev">
		    <span class="icon-prev"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class=" right carousel-control" href="#carouselExampleControls" role="button" data-slide="next">
		    <span class="icon-next"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
	</div>
<hr style="border:1px solid #9DD8F7;">


<div class="row mission-vision">
	<div class="container-fluid">
		<div class="col-md-4 text-center">
			<div class="title-def">
				<i class="fas fa-globe-africa fa-3x image-def"></i>
			</div>

			<div class="content-def">
				<h4 class="core-content">Vision</h4>
				<p>To make Disciples of all nations. (Matthew 28:19) : "Go therefore and make disciples of all nations, baptizing them in the name of the Holyspirit, teaching them to observe all that I have commanded you; and lo I am with you to the end of age." Amen
				</p>
			</div>
		</div>

		<div class="col-md-4 text-center">
			<div>
			<i class="fas fa-church fa-3x image-def"></i>
			</div>

			<div class="content-def">
				<h4 class="core-content">Mission Statement</h4>
				<p>To be a church that rightfully and effectively declares the message of the scripture that is socially and spiritually relevant, equipping saints to do the work of the ministry.
				</p>
			</div>
		</div>

		<div class="col-md-4 text-center">
			<div class="title-def">
				<i class="fas fa-pray fa-3x image-def"></i>
			</div>

			<div class="content-def">
				<h4 class="core-content">Purpose</h4>
				<P>To bring People to Christ and to the membership of His family, disciples and equip them for the work of the ministry. (Ephesians 4:12)
				<span id="dots">...</span></P>
				<div id="more">
					<P>To add value in people's lives through teaching biblical principles and being a role model</P>

					<P>To develop a Kingdom community that impacts other communities. Example Academic Community, Business community etc.</P>
				</div>

				<button class="btn btn-info" onclick="myFunction()" id="myBtn">Readmore</button>
			</div>
		</div>
	</div>
</div>
<hr style="border:1px solid #9DD8F7;">
<div class="row mission-vision">
	<div class="container-fluid">
		<h4 class="text-center core-title">OUR CORE VALUES</h4>
			<div class="values-row row">
				<div class="value-card col-md-4">
						<div class="card">
							<%= image_tag("family.jpg", class: "card-img-top d-block w-100 c-image") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">We Are a Family</h3>

						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>

				<div class="value-card col-md-4">
						<div class="card">
							<%= image_tag("excellent_service.jpg", class: "card-img-top d-block w-100 c-image") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">Excellence in Service</h3>
						    
						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>

				<div class="value-card col-md-4">
					<div class="card">
							<%= image_tag("biblical-techings.jpg", class: "card-img-top d-block w-100 c-image") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">Sound Biblical Teachings</h3>
						    
						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>
			</div>

			<div class="values-row row">
				<div class="value-card col-md-4">
						<div class="card">
							<%= image_tag("education.jpg", class: "card-img-top d-block w-100 c-image") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">Learning</h3>
						   
						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>

				<div class="value-card col-md-4">
					<div class="card">
							<%= image_tag("god_centered.jpg", class: "card-img-top d-block w-100 c-image") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">God Centered Worship</h3>
						    
						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>

				<div class="value-card col-md-4">
						<div class="card ">
							<%= image_tag("children_mini.jpg", class: "card-img-top d-block w-100 c-image rounded border border-primary") %>
						 <!--  <img class="card-img-top" src="..." alt="Card image cap"> -->
						  <div class="card-body text-center">
						    <h3 class="card-title text-center">Children Ministry</h3>
						    <%= link_to 'Read More', about_path, class: "btn btn-info" %>
						  </div>
						</div>
				</div>
			</div>
	</div>
</div>
<hr style="border:1px solid #9DD8F7;">

<div class="blog-sect text-center">
	<h4 class="core-title">WORD FROM THE PASTOR'S DESK</h4>
	<%if !@blogs.empty? %>
		<h4><%= blog_title(0) %></h4>
		<p><%= blog_text_teaser(0)%></p>
		<%= link_to "Read more", blog_path(blog_helper(0)), class: "btn btn-info" %>
	<% else %>
		<p>We writing something good for you.</p>
	<% end %>
</div>
<hr style="border:1px solid #9DD8F7;">
<div class="video-sect text-center">
	<h4 class="core-title">SERMONS AND SONGS</h4>
	<%if !@videos.empty? %>
		<div class="row" style="margin-bottom:10px;">
			<% @videos.first(3).each do |video| %>
				<div class="col-md-4">
					<iframe src='https://www.youtube.com/embed/<%= video.url.split('/').last %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
				</div>
			<% end %>
		</div>
			<%= link_to "View More Videos", videos_path, class: "btn btn-info" %>
	<% else %>
		<p>We will upload our videos soon.</p>
	<% end %>
	</div>

<div class="modal fade" id="giveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title text-center" id="exampleModalLabel">Giving: Tithes, Offerings, Projects</h2>
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->
      </div>
      <div class="modal-body">

       	<div class="item">
		      <%= image_tag("mpesa_church.png", class: "d-block w-100 c-image") %>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-info">Save changes</button> -->
      </div>
    </div>
  </div>
</div>