config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',	 		to: 'static_pages#help'
  get '/about',	 		to: 'static_pages#about'
  get '/contact', 		to: 'static_pages#contact'
  get '/signup',	    to: 'users#new'
  get '/login',	    	to: 'sessions#new'
  post '/login',	    to: 'sessions#create'
  delete '/logout',	    to: 'sessions#destroy'
  resources :users 
  resources :blogs
  resources :videos
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="#">PEFA Church Kayole B website</a>
		developed and maintained by the<a href="#">PEFA Church Kayole B Media Team</a>
	</small>
	<nav class="navbar navbar-inverse footer-nav text-center">
		<ul class="nav navbar-nav">
			<li><%= link_to "About",about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="#">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
 <header id="top-bar" class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <nav>
          <%= link_to "PEFA Church Kayole B", root_path, :id => 'logo' %>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" 
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-exampanded="false">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </div>

          <ul class="nav navbar-nav navbar-left collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Departments", root_path %></li>
            <li><%= link_to "Blog", blogs_path %></li>
            <li><%= link_to "Sermons & Songs", videos_path %></li>
            <li><%= link_to "Events", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", "#" %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out
                      ", logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path, method: :get %></li>
            <% end %>
          </ul>

          <div>
            <ul id="social-icons" class="nav navbar-nav navbar-right">
                 <li><a href="https://www.facebook.com/PEFA-Church-Kayole-B-100273028255437" target="_blank"><i class="fab fa-facebook fa-lg"></i></a></li>
                 <li><a href="https://twitter.com/BPefa" target="_blank"><i class="fab fa-twitter fa-lg"></i></a></li>
                 <li><a href="https://www.instagram.com/pkb_church/" target="_blank"><i class="fab fa-instagram fa-lg"></i></a></li>
                 <li><a href="https://www.youtube.com/channel/UC7vtuUpN6xbFruzRnk3ewjw" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></li>
             </ul>
           </div>
        </nav>
      </div>
</header>

<div class="row contacts-bar">
    <div class="col-md-6">
      <nav id="brand-bar" class="nav navbar-nav navbar-left  brand-nav">
        <a class="navbar-brand" href="#">
          <%= image_tag("youtube-logo-pefa-kayole-b.png", width: "60", height: "60", alt:"") %>
        </a>
        <p id="brand-title">PEFA CHURCH KAYOLE B</p>
        <p id ="brand-vision" class="brand-nav" style="margin-left:23px;">Making Disciples of All Nations</p>
      </nav>
      <p id ="brand-vision-mobile" class="brand-nav">Making Disciples of All Nations</p>
    </div>

    <div class="col-md-6">
      <ul id="contacts-nav" class="nav navbar-nav navbar-right">
        <li>
            <p><i class="far fa-envelope fa-3x"></i>
          </p>
          </li>
          <li> 
            <p>Email Us At</p>
            <p><a class="contacts-link"href = "mailto: youthpkb@gmail.com">pefa.kb@gmail.com</a></p>
          </li>
          <li>
              <p><i class="fas fa-phone-alt fa-3x"></i>
            </li>
            <li> 
              <p>Call Us Now!</p>
              <p><a class="contacts-link" href = "tel: 0723******">0723256785</a></p>
            </li>
            <li>
                <p><a href="#" class="btn btn-info btn-lg give-button" data-toggle="modal" data-target="#giveModal" tabindex="-1" role="button" aria-disabled="true">Give</a></p>
              </li>
      </ul>
    </div>
  </div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert=#{message_type}" )%>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>